language: node_js
# required for now due to issues related to spectre  https://github.com/travis-ci/travis-ci/issues/9024
sudo: required
node_js:
  - stable
dist: trusty
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
after_script:
  - npm run coveralls
script: # script will result in a failed build if this fails
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: mdvorscak-memory-match.surge.sh 